apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: "Voyages Scolaires"
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost:8080
  DB_CONNECTION: mysql
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_DATABASE: voyages_scolaires
  SESSION_DRIVER: database
  LOG_CHANNEL: stderr
