apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: ghcr.io/neighley/voyages-scolaires-justine-maudeva:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secrets
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 5
