apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
stringData:
  APP_KEY: # TODO: docker compose exec app php artisan key:generate --show
  DB_USERNAME: voyages_user
  DB_PASSWORD: voyages_password
  DB_ROOT_PASSWORD: root_secret_password
